/**
 * EvidenceValidationView — the Phase 13D.1 Evidence / Validation operator view.
 *
 * Replaces the honest Phase 13B/13C placeholder Evidence / Validation entry
 * with a real read-only view. The view's job is to point reviewers at the
 * static evidence preserved in the repository that backs StoryTime's
 * portfolio claims — without ever pretending to be a live CI dashboard,
 * without rerunning tests in the browser, and without fabricating fresh
 * green/red status indicators.
 *
 * Everything here is static. The component reads only from `evidenceAdapter`
 * (descriptive copy + repository-relative paths + counts derived from the
 * locked Phase 13C deterministic export). No `fetch`, no `axios`, no
 * runtime parsing of `docs/`, no live progress bars.
 *
 * The literal disclaimer "STATIC PORTFOLIO DATA — NOT A LIVE CI/CD
 * DASHBOARD" appears in the source so the Phase 13D.1 grep gate
 * (`grep -rn "STATIC PORTFOLIO DATA" frontend/src`) finds it.
 */

import {
  DATA_SOURCE_FRAMING,
  DATA_SOURCE_SNAPSHOTS,
  EVIDENCE_CATEGORIES,
  EVIDENCE_DISCLAIMER,
  EVIDENCE_EXPORT_FACTS,
  EVIDENCE_REPO_REFERENCES,
  EVIDENCE_TALKING_POINTS,
} from "../data/evidenceAdapter";
import { ActionPreviewPanel } from "./ActionPreviewPanel";
import styles from "./EvidenceValidationView.module.css";

export function EvidenceValidationView(): JSX.Element {
  return (
    <section className={styles.container}>
      {/* ── Page header ── */}
      <header className={styles.header}>
        <p className={styles.eyebrow}>Operator view · Phase 13D.1</p>
        <h2 className={styles.title}>Evidence / Validation</h2>
        <p className={styles.lede}>
          A reviewer-facing index of where StoryTime's claims are supported
          inside this repository. Each row points to a committed file — open
          it in your editor to verify the claim directly.
        </p>
      </header>

      {/* ── Mandatory disclaimer banner ─────────────────────────────────
          The exact phrase below is required by the Phase 13D.1 contract.
          Do not edit the wording: a grep verification gate looks for it.
          ───────────────────────────────────────────────────────────────── */}
      <div
        className={styles.disclaimerBanner}
        role="note"
        aria-label="Static portfolio data disclaimer"
      >
        <strong className={styles.disclaimerLabel}>Notice</strong>
        <span className={styles.disclaimerText}>{EVIDENCE_DISCLAIMER}</span>
      </div>

      <p className={styles.disclaimerNote}>
        This page does not rerun any test or contact any backend. It only
        names the static files in the repository where the evidence lives.
        Counts come from the bundled Demo Snapshot.
      </p>

      {/* ── Scope strip with static facts from the locked export ── */}
      <div className={styles.factGrid}>
        <div className={styles.factCard}>
          <span className={styles.factLabel}>Demo Snapshot schema</span>
          <span className={styles.factValue}>
            {EVIDENCE_EXPORT_FACTS.schemaVersion}
          </span>
        </div>
        <div className={styles.factCard}>
          <span className={styles.factLabel}>Generated by</span>
          <span className={styles.factValue}>
            {EVIDENCE_EXPORT_FACTS.generatedBy}
          </span>
        </div>
        <div className={styles.factCard}>
          <span className={styles.factLabel}>Runs in scope</span>
          <span className={styles.factValue}>
            {EVIDENCE_EXPORT_FACTS.runCount}
          </span>
        </div>
        <div className={styles.factCard}>
          <span className={styles.factLabel}>Failure queue items</span>
          <span className={styles.factValue}>
            {EVIDENCE_EXPORT_FACTS.failureQueueCount}
          </span>
        </div>
        <div className={styles.factCard}>
          <span className={styles.factLabel}>Governance rows</span>
          <span className={styles.factValue}>
            {EVIDENCE_EXPORT_FACTS.governanceRowCount}
          </span>
        </div>
      </div>

      {/* ── Claims vs proof grid ── */}
      <section className={styles.section}>
        <h3 className={styles.sectionHead}>Claims vs proof</h3>
        <p className={styles.sectionLede}>
          What StoryTime says about itself, and the static file in the
          repository where a reviewer can verify it.
        </p>
        <div className={styles.categoryGrid}>
          {EVIDENCE_CATEGORIES.map((category) => (
            <article key={category.id} className={styles.categoryCard}>
              <h4 className={styles.categoryTitle}>{category.title}</h4>
              <p className={styles.categoryClaimLabel}>Claim</p>
              <p className={styles.categoryClaim}>{category.claim}</p>
              <p className={styles.categoryProofLabel}>Where to verify</p>
              <p className={styles.categoryProof}>{category.proof}</p>
              <ul className={styles.categoryPaths}>
                {category.paths.map((path) => (
                  <li key={path}>
                    <code className={styles.pathCode}>{path}</code>
                  </li>
                ))}
              </ul>
            </article>
          ))}
        </div>
      </section>

      {/* ── Data Source / Demo Snapshot framing ── */}
      <section className={styles.section}>
        <h3 className={styles.sectionHead}>{DATA_SOURCE_FRAMING.heading}</h3>
        <p className={styles.sectionLede}>{DATA_SOURCE_FRAMING.body}</p>
        <div className={styles.snapshotGrid}>
          {DATA_SOURCE_SNAPSHOTS.map((snapshot) => (
            <article
              key={snapshot.id}
              className={
                snapshot.current
                  ? `${styles.snapshotCard} ${styles.snapshotCardCurrent}`
                  : `${styles.snapshotCard} ${styles.snapshotCardFuture}`
              }
            >
              <header className={styles.snapshotHead}>
                <h4 className={styles.snapshotTitle}>{snapshot.label}</h4>
                {snapshot.current ? (
                  <span
                    className={`${styles.snapshotPill} ${styles.snapshotPillCurrent}`}
                  >
                    current
                  </span>
                ) : (
                  <span
                    className={`${styles.snapshotPill} ${styles.snapshotPillFuture}`}
                  >
                    future · not implemented
                  </span>
                )}
              </header>
              <p className={styles.snapshotDescription}>
                {snapshot.description}
              </p>
            </article>
          ))}
        </div>
        <p className={styles.snapshotCaption}>
          {DATA_SOURCE_FRAMING.diagramCaption}
        </p>
      </section>

      {/* ── Repository references ── */}
      <section className={styles.section}>
        <h3 className={styles.sectionHead}>Repository references</h3>
        <p className={styles.sectionLede}>
          A short ordered list of files inside this artifact a reviewer can
          open directly. The view does not fetch them; open them in your
          editor.
        </p>
        <ul className={styles.refList}>
          {EVIDENCE_REPO_REFERENCES.map((ref) => (
            <li key={ref.id} className={styles.refRow}>
              <code className={styles.refPath}>{ref.path}</code>
              <span className={styles.refNote}>{ref.note}</span>
            </li>
          ))}
        </ul>
      </section>

      {/* ── Demo-mode action previews (Phase 13E) ── */}
      <section className={styles.section}>
        <ActionPreviewPanel
          availablePreviews={[
            "preview-refresh-export",
            "preview-regenerate-operator-report",
          ]}
          view="Evidence / Validation"
        />
      </section>

      {/* ── Talking points ── */}
      <section className={styles.section}>
        <h3 className={styles.sectionHead}>What this view is and is not</h3>
        <ul className={styles.talkingList}>
          {EVIDENCE_TALKING_POINTS.map((point, idx) => (
            <li key={idx} className={styles.talkingItem}>
              {point}
            </li>
          ))}
        </ul>
      </section>
    </section>
  );
}
