/**
 * StoryTime — frontend data adapter (Phase 13C).
 *
 * This module is the single seam between the deterministic backend static
 * export and the React components. It:
 *
 *  1. statically imports the committed export JSON
 *     (`storytime-demo-export.json`, produced by the backend command
 *     `storytime export-demo-ui` — module `storytime.operator_export`);
 *  2. types it as the `StaticDemoExport` contract envelope;
 *  3. derives the UI-ready view data the components need — in particular the
 *     runs-list summaries, which the export does not store because they are a
 *     pure projection of the run details.
 *
 * "Backend owns truth, frontend owns understanding": the export is the truth;
 * this adapter is the understanding layer. React components import from here,
 * never from the raw JSON, so a future change to the export shape is absorbed
 * in this one file.
 *
 * This is a static, read-only data boundary. The JSON is imported at build
 * time — there is no `fetch`, no `axios`, no network call, and no live backend.
 */

import type {
  FailureQueueItem,
  PipelineRunDetail,
  PipelineRunSummary,
  StaticDemoExport,
  StoryTimeProjectSummary,
} from "../types/storytime";
import rawExport from "./storytime-demo-export.json";

/**
 * The static export, typed as the contract envelope. The JSON is generated by
 * the backend from fixed demo data, so this cast reflects a real, deterministic
 * contract rather than an unchecked assumption; the contract tests on the
 * backend side guard the shape.
 */
const exportData = rawExport as unknown as StaticDemoExport;

/** Export metadata — schema version and provenance, for display/diagnostics. */
export const EXPORT_META = {
  schemaVersion: exportData.schemaVersion,
  generatedBy: exportData.generatedBy,
  exportKind: exportData.exportKind,
} as const;

/** The portfolio project summary. */
export const DEMO_PROJECT: StoryTimeProjectSummary = exportData.project;

/** All run-detail records, in export order. */
export const DEMO_RUN_DETAILS: PipelineRunDetail[] = exportData.runs;

/** The failure / review queue projection. */
export const DEMO_FAILURE_QUEUE: FailureQueueItem[] = exportData.failureQueue;

/**
 * The runs-list summary projection, derived here from the run details. The
 * export intentionally does not store this — it is pure understanding the
 * frontend owns.
 */
export const DEMO_RUN_SUMMARIES: PipelineRunSummary[] = DEMO_RUN_DETAILS.map(
  (run) => ({
    id: run.id,
    label: run.label,
    status: run.status,
    governanceStatus: run.governance.status,
    createdAt: run.createdAt,
    updatedAt: run.updatedAt,
    needsAttention: run.status === "blocked" || run.status === "failed",
  }),
);

/** Look up a run-detail record by id. */
export function findRunDetail(id: string): PipelineRunDetail | undefined {
  return DEMO_RUN_DETAILS.find((run) => run.id === id);
}
