/**
 * demoWalkthroughAdapter — static view-model for the Demo Walkthrough /
 * Reviewer Story Path view (refreshed in Phase 13K to tell the governed
 * local-chain story and stay consistent with the canonical written
 * walkthrough, docs/demo-walkthrough.md).
 *
 * All long-form walkthrough content lives in this adapter, not in the
 * `DemoWalkthroughView` component. The view is a presentation shell that
 * iterates over the data exported here. This separation is a deliberate
 * design choice so that the route definitions, step
 * notes, architecture checkpoints, deferred-work explanations, talking
 * points, and repository references stay reviewable as data rather than
 * being buried in JSX.
 *
 * The adapter is intentionally static. It imports existing typed exports
 * from `./adapter` where useful (`EXPORT_META`, `DEMO_PROJECT`,
 * `DEMO_RUN_SUMMARIES`, `DEMO_FAILURE_QUEUE`) and exposes a handful of
 * arrays / records the view consumes. There is no `fetch`, no `axios`,
 * no runtime parsing of docs, no API call, and no mutation. Steps that
 * point to a specific pipeline run name it by stable id
 * (`run-2026-0518-golden` for the golden-path run; `run-2026-0520-review`
 * for the review-required run) so the reviewer is never asked to guess
 * which run proves the point. Both ids are present in the locked Phase
 * `frontend/src/data/storytime-demo-export.json` and are stable in the
 * committed static export the public demo reads.
 */

import {
  DEMO_FAILURE_QUEUE,
  DEMO_PROJECT,
  DEMO_RUN_SUMMARIES,
  EXPORT_META,
} from "./adapter";
import type { View } from "../navigation";

/* ─────────────────────── stable run ids ─────────────────────── */

/**
 * Stable ids for the two demo runs in the committed export. These are
 * referenced from walkthrough steps so the reviewer can drill into the
 * exact run a step is talking about without guessing.
 */
export const GOLDEN_RUN_ID = "run-2026-0518-golden" as const;
export const REVIEW_RUN_ID = "run-2026-0520-review" as const;

/* ─────────────────────── route definitions ─────────────────────── */

/**
 * The four reviewer routes the Demo Walkthrough view offers. They are
 * switched by a simple segmented control backed by `useState<RouteId>`
 * inside the view — no router, no Context, no persistence.
 */
export type RouteId =
  | "five-min"
  | "ten-min"
  | "deep-dive"
  | "self-guided"
  | "governed-chain";

/**
 * A single step in a walkthrough route. A step EITHER navigates to a
 * top-level view (`targetView`) OR opens the Pipeline Run Detail view
 * focused on a specific run (`inspectRunId`). The presentation shell
 * picks the appropriate App-level callback based on which field is
 * present.
 */
export interface WalkthroughStep {
  readonly id: string;
  readonly title: string;
  /** Plain-English target view label, shown as a tag on the step. */
  readonly targetLabel: string;
  readonly targetView: View;
  /**
   * If set, the step opens the Pipeline Run Detail view focused on this
   * run id. The presentation shell calls `onInspectRun(inspectRunId)`
   * instead of `onNavigate(targetView)`.
   */
  readonly inspectRunId?: string;
  /** A short sentence describing what to inspect on the target view. */
  readonly whatToInspect: string;
  /** A short sentence describing what this step proves. */
  readonly whatItProves: string;
  /** Short bullet-point talking points the reviewer can speak to. */
  readonly talkingPoints: readonly string[];
  /** Optional inline run context (e.g. stable id and label). */
  readonly runContext?: string;
}

export interface Route {
  readonly id: RouteId;
  readonly label: string;
  readonly purpose: string;
  readonly approximateMinutes: number;
  readonly intro: string;
  readonly steps: readonly WalkthroughStep[];
}

/* ─────────────────────── steps used by multiple routes ──────────── */

const stepOverview: WalkthroughStep = {
  id: "overview",
  title: "Start at the Overview",
  targetLabel: "Overview",
  targetView: "home",
  whatToInspect:
    "The project summary, the demo-snapshot framing in the header, " +
    "and the link into the pipeline run list.",
  whatItProves:
    "StoryTime is a real local pipeline that emitted a deterministic " +
    "operator-facing export; the GUI is reading that committed export " +
    "snapshot, not calling a server.",
  talkingPoints: [
    "The header carries a Demo Snapshot data-source chip — the data " +
      "is committed, not live.",
    "The static demo banner at the very top names this as a static, " +
      "read-only build with no backend.",
    `Schema version ${EXPORT_META.schemaVersion} is generated by ` +
      `\`${EXPORT_META.generatedBy}\`; everything below ultimately ` +
      "derives from that JSON.",
  ],
};

const stepGoldenRun: WalkthroughStep = {
  id: "golden-run",
  title: "Inspect the golden-path run",
  targetLabel: "Pipeline Run Detail",
  targetView: "runs",
  inspectRunId: GOLDEN_RUN_ID,
  runContext: `Run \`${GOLDEN_RUN_ID}\` — Aesop "The Fox and the Grapes" (CC0 demo text), status \`succeeded\`.`,
  whatToInspect:
    "The stage timeline, the per-stage timings, the published artifacts, " +
    "and the governance summary card.",
  whatItProves:
    "The pipeline runs end-to-end on CC0 demo text and produces a " +
    "publishable artifact with full observability. There is no live " +
    "telemetry — the timings and gate outcomes were emitted by the " +
    "backend run and frozen into the export.",
  talkingPoints: [
    "Each stage has measured timing and a clear status — not a fake.",
    "The artifact and governance summary are static snapshots of the " +
      "real run, not a re-execution.",
    "This is what an operator would see today on a successful run.",
  ],
};

const stepReviewRun: WalkthroughStep = {
  id: "review-run",
  title: "Inspect the review-required run",
  targetLabel: "Pipeline Run Detail",
  targetView: "runs",
  inspectRunId: REVIEW_RUN_ID,
  runContext: `Run \`${REVIEW_RUN_ID}\` — an untitled community submission held for governance review.`,
  whatToInspect:
    "The status badge, the governance gate that blocked the run, and " +
    "the disabled review-action affordances at the bottom of the page.",
  whatItProves:
    "Governance fails closed: when source / safety can't be confirmed, " +
    "the pipeline blocks rather than publishing. The review UI is " +
    "intentionally disabled in the GUI — review approval is not a " +
    "frontend action today.",
  talkingPoints: [
    "Fail-closed governance is the policy, not an afterthought.",
    "The disabled action cards are real `<button disabled>` elements " +
      "with no `onClick` handlers — they cannot be coaxed into firing.",
    "Approval / rejection happens out-of-band, not through this GUI; " +
      "that boundary belongs to a future reviewed phase.",
  ],
};

const stepGovernance: WalkthroughStep = {
  id: "governance",
  title: "Open Governance / Safety",
  targetLabel: "Governance / Safety",
  targetView: "governance",
  whatToInspect:
    "The active policies, the gate decisions for each run, and any " +
    "needs-review entries.",
  whatItProves:
    "Governance is a first-class operator view, not a hidden detail. " +
    "Reviewers can see which policy fired on which run and why.",
  talkingPoints: [
    "Governance is observable to operators — they don't have to grep logs.",
    "The 'inspect this run' affordance jumps back to the specific run " +
      "that triggered the decision.",
    "All affordances that would change governance state remain visibly " +
      "disabled; nothing on the page mutates.",
  ],
};

const stepFailure: WalkthroughStep = {
  id: "failure",
  title: "Open Failure / Recovery",
  targetLabel: "Failure / Recovery",
  targetView: "failure",
  whatToInspect:
    "The failure queue, the reason / since columns, and the visibly " +
    "disabled retry / acknowledge affordances.",
  whatItProves:
    "Operational failure modes are observable: the operator can see " +
    `${DEMO_FAILURE_QUEUE.length} queued item(s) and the reason. The ` +
    "retry / acknowledge / dismiss controls are intentionally disabled " +
    "in the GUI — those belong to a deferred mutation boundary in a " +
    "future reviewed phase.",
  talkingPoints: [
    "The queue is a real projection of the export, not a stub.",
    "Disabled affordances are honest about the static boundary — they " +
      "do not promise automated retry that doesn't exist yet.",
    "Recovery decisions today happen in the CLI / runbook, not the GUI.",
  ],
};

const stepEvidence: WalkthroughStep = {
  id: "evidence",
  title: "Open Evidence / Validation",
  targetLabel: "Evidence / Validation",
  targetView: "evidence",
  whatToInspect:
    "The static-portfolio-snapshot disclaimer (a static portfolio " +
    "snapshot, not a live CI/CD dashboard), the evidence categories, the " +
    "Data Source / Demo Snapshot framing, and the repository-relative " +
    "evidence references.",
  whatItProves:
    "The portfolio is honest about what it is: a static build over a " +
    "committed export, evidenced by repository files (verification log, " +
    "static export contract, deferred-work register, phase history, " +
    "guards). Active and Candidate are framed as data snapshots, not " +
    "deployment environments.",
  talkingPoints: [
    "The disclaimer is the single most important honesty signal in the " +
      "portfolio.",
    "Each evidence claim points to a real repository file the reviewer " +
      "can open.",
    "The public site presents one committed demo snapshot; any future " +
      "snapshots would be added only as committed, reviewable static data " +
      "— not live deployment environments, and snapshot switching is not " +
      "implemented.",
  ],
};

/* ─────────────────────── deep-dive specific steps ─────────────────── */

const stepStaticExportBoundary: WalkthroughStep = {
  id: "static-export-boundary",
  title: "Understand the static export boundary",
  targetLabel: "Evidence / Validation",
  targetView: "evidence",
  whatToInspect:
    "The Data Source / Demo Snapshot section and the reference to " +
    "`docs/frontend-static-export-contract.md`.",
  whatItProves:
    "The backend (`src/storytime/operator_export.py`) writes a typed, " +
    "deterministic JSON snapshot via `storytime export-demo-ui`; the " +
    "frontend reads only that committed JSON. The contract is locked " +
    "and the export is the byte-identical, stable source of truth for " +
    "the public static demo.",
  talkingPoints: [
    "Backend owns truth (the runtime run produces the JSON).",
    "Frontend owns understanding (the GUI projects the JSON into views).",
    "The export schema is versioned and walked under test " +
      "(`tests/test_operator_export.py`).",
  ],
};

const stepAdapterLayer: WalkthroughStep = {
  id: "adapter-layer",
  title: "Look at the adapter / view-model layer",
  targetLabel: "Pipeline Run Detail",
  targetView: "runs",
  whatToInspect:
    "Open `frontend/src/data/adapter.ts`, `governanceAdapter.ts`, " +
    "`failureAdapter.ts`, `evidenceAdapter.ts`, and this file " +
    "(`demoWalkthroughAdapter.ts`) — each view consumes its own typed " +
    "view-model derived from the committed export.",
  whatItProves:
    "View components are thin presentation shells. Domain logic and " +
    "long-form content live in small, typed adapters. No view talks to " +
    "the backend or fetches anything at runtime.",
  talkingPoints: [
    "Each adapter has a narrow, typed surface — easy to review.",
    "Adapters are pure functions over committed JSON; they have no " +
      "side effects.",
    "This layout makes a future controlled-mutation surface easier to " +
      "introduce safely.",
  ],
};

const stepDisabledActionDiscipline: WalkthroughStep = {
  id: "disabled-action-discipline",
  title: "Inspect disabled-action discipline",
  targetLabel: "Failure / Recovery",
  targetView: "failure",
  whatToInspect:
    "The disabled future-action cards on Failure / Recovery, Governance " +
    "/ Safety, and the Pipeline Run Detail page. Open " +
    "`DisabledFutureActionCard.tsx` if you want to read the component.",
  whatItProves:
    "Every action that would mutate state is a real " +
    "`<button disabled={true}>` with no `onClick` handler and no fake " +
    "mutation prop. There is no clickable surface that lies about what " +
    "happens.",
  talkingPoints: [
    "Disabled means disabled — not greyed-out clickable.",
    "The component is shared, so the discipline is enforced in one place.",
    "This is the readiness contract a future reviewed phase will satisfy " +
      "when a real mutation surface is added behind a gate.",
  ],
};

const stepStateDisciplineGuard: WalkthroughStep = {
  id: "state-discipline-guard",
  title: "Read the state-discipline guard evidence",
  targetLabel: "Evidence / Validation",
  targetView: "evidence",
  whatToInspect:
    "The reference to `tests/test_failure_mode_regression.py` in the " +
    "Evidence view. Open it to see the current-phase, last-locked, " +
    "no-overclaim, no-future-claim, and append-only history tests.",
  whatItProves:
    "The State Preservation Bundle is not vibes — the current-phase " +
    "expectations are mechanically enforced in CI-style tests that " +
    "advance only under an explicitly authorized exception each round.",
  talkingPoints: [
    "The guard prevents the docs from drifting ahead of reality.",
    "The append-only history makes phase records auditable.",
    "Each round adds, never rewrites, the lock-record checks.",
  ],
};

const stepDeferredBoundary: WalkthroughStep = {
  id: "deferred-mutation-boundary",
  title: "Understand the deferred mutation boundary",
  targetLabel: "Evidence / Validation",
  targetView: "evidence",
  whatToInspect:
    "The 'What is intentionally deferred' section on this Demo " +
    "Walkthrough page, then the evidence reference to " +
    "`docs/frontend-gui-deferred-work-register.md`.",
  whatItProves:
    "Mutation, live integration, snapshot switching, and a standalone " +
    "Architecture Story page are tracked as explicit deferred items, " +
    "not pretended-to.",
  talkingPoints: [
    "Deferred is named, not hidden — the register is a real document.",
    "Backend cloud runtime is the next gated work; it is deferred to a " +
      "future reviewed phase and not implied to exist behind the current " +
      "UI.",
    "Each deferred item names its risk profile and why it must be " +
      "gated.",
  ],
};

/* ─────────────────────── self-guided specific steps ─────────────── */

const stepSelfGuidedOrientation: WalkthroughStep = {
  id: "self-guided-orientation",
  title: "Orient yourself first",
  targetLabel: "Overview",
  targetView: "home",
  whatToInspect:
    "The Overview, the static demo banner, and the header Data Source " +
    "chip — read each carefully before clicking anywhere.",
  whatItProves:
    "Even without a guide, you can tell from the chrome alone that " +
    "this is a static build over a committed export.",
  talkingPoints: [
    "If you only have one minute: the demo banner answers 'is this live?'.",
    "The chip tells you 'where does this data come from?'.",
    "Everything else in the GUI is a projection of that one data source.",
  ],
};

const stepSelfGuidedActionBoundary: WalkthroughStep = {
  id: "self-guided-action-boundary",
  title: "Check what is and isn't clickable",
  targetLabel: "Failure / Recovery",
  targetView: "failure",
  whatToInspect:
    "Look for the disabled action cards on Failure / Recovery and " +
    "Governance / Safety. Try clicking them — nothing fires.",
  whatItProves:
    "Disabled actions are honest. The GUI does not pretend to retry, " +
    "approve, or dismiss anything. Those belong to a future reviewed phase.",
  talkingPoints: [
    "If a button is greyed out, it is genuinely off — no hidden handler.",
    "What the GUI does not do is at least as important as what it does.",
    "Future mutation is gated behind a separate review round, not " +
      "smuggled in.",
  ],
};

const stepSelfGuidedEvidence: WalkthroughStep = {
  id: "self-guided-evidence",
  title: "Read the evidence page last",
  targetLabel: "Evidence / Validation",
  targetView: "evidence",
  whatToInspect:
    "The Evidence / Validation view and every repository-relative " +
    "reference on it.",
  whatItProves:
    "The portfolio's claims are backed by real files in the repository " +
    "— verification log, contract docs, deferred-work register, phase " +
    "history, append-only canonical state, and CI-style guard tests.",
  talkingPoints: [
    "If something feels too clean, open the referenced file and verify.",
    "The evidence is local and inspectable — no external dashboard.",
    "Static portfolio data is a feature, not a limitation, for the " +
      "current phase.",
  ],
};

/* ─────────────────────── ROUTES (the public surface) ─────────────── */

/* ─────────────────────── governed local-chain steps (Phase 13K) ── */

const stepModes: WalkthroughStep = {
  id: "modes",
  title: "Read the four modes and the boundary legend",
  targetLabel: "Overview",
  targetView: "home",
  whatToInspect:
    "The mode overview and boundary legend on the Overview: Static Demo, " +
    "Local Bridge, Governed Local TTS Proof, and Manual Snapshot Reload.",
  whatItProves:
    "StoryTime separates static demo data, backend-owned local execution, " +
    "and governed backend proof. The browser is an operator surface, not the " +
    "source of truth.",
  talkingPoints: [
    "Three boundaries: static demo, local bridge, backend proof.",
    "The backend owns execution and state; the browser observes and submits " +
      "narrow operator intents.",
  ],
};

const stepBridgeReadiness: WalkthroughStep = {
  id: "bridge-readiness",
  title: "Check the loopback bridge readiness and queue",
  targetLabel: "Local Bridge",
  targetView: "bridge",
  whatToInspect:
    "The operator workflow and the read-only readiness / queue / lifecycle " +
    "panels on the Local Bridge view.",
  whatItProves:
    "Bridge observability is read-only and loopback-only; it is optional " +
    "infrastructure, not exposed to the public web.",
  talkingPoints: [
    "Probes are GET-only and operator-initiated.",
    "No polling, sockets, or background refresh.",
  ],
};

const stepControlledRetry: WalkthroughStep = {
  id: "controlled-retry",
  title: "Understand the one controlled retry",
  targetLabel: "Local Bridge",
  targetView: "bridge",
  whatToInspect:
    "The controlled retry panel: it submits exactly one action type, " +
    "retry_failed_stage, and reports acceptance.",
  whatItProves:
    "In local execution, the only state-changing action the browser " +
    "submits is one controlled retry; the hosted public demo submits no " +
    "runtime work and gates this surface to a local-only notice. " +
    "Acceptance is not success — a 202 means queued, so the operator " +
    "observes the lifecycle.",
  talkingPoints: [
    "One action only: retry_failed_stage.",
    "Acceptance is not success; observe the lifecycle.",
  ],
};

const stepManualReload: WalkthroughStep = {
  id: "manual-reload",
  title: "Manually reload the snapshot",
  targetLabel: "Local Bridge",
  targetView: "bridge",
  whatToInspect:
    "The static export reload panel: an operator-triggered, validated " +
    "read-model refresh.",
  whatItProves:
    "The visible snapshot is transient and refreshes only on a manual " +
    "reload. It is a read-model refresh, not a live sync, and not proof a job " +
    "succeeded.",
  talkingPoints: [
    "Manual, validated, all-or-nothing read-model replacement.",
    "No automatic or background sync.",
  ],
};

const stepTtsProof: WalkthroughStep = {
  id: "tts-proof",
  title: "Inspect the governed local TTS proof (read-only)",
  targetLabel: "Local Bridge",
  targetView: "bridge",
  whatToInspect:
    "The read-only TTS proof summary: provider mode, the deferred " +
    "provider-backed adapter, the approved fixture and text-hash concepts, " +
    "and the artifact / manifest / audit lifecycle.",
  whatItProves:
    "StoryTime generates a local audio artifact through a governed, " +
    "observable, auditable backend boundary. The provider is the mock; " +
    "provider-backed audio remains deferred; generation is backend/CLI-owned " +
    "and the browser cannot trigger it. Mock output is labeled mock.",
  talkingPoints: [
    "Mock provider; provider-backed audio remains deferred.",
    "Artifact + manifest + audit/event evidence; raw text is never stored.",
    "The browser cannot trigger generation; this is read-only evidence.",
  ],
};

export const ROUTES: readonly Route[] = [
  {
    id: "five-min",
    label: "5-minute scan",
    purpose: "Fast reviewer scan",
    approximateMinutes: 5,
    intro:
      "Four stops, roughly one minute each. Confirms the static boundary, " +
      "the golden-path run, the governance posture, and the evidence " +
      "frame. Skip the deep architecture and disabled-action discussion.",
    steps: [stepOverview, stepGoldenRun, stepGovernance, stepEvidence],
  },
  {
    id: "ten-min",
    label: "10-minute demo",
    purpose: "Stronger SE-style demo",
    approximateMinutes: 10,
    intro:
      "The route an SE leader is most likely to want. Six stops covering " +
      "the golden path, the review-required path, governance, failure / " +
      "recovery, and the evidence frame.",
    steps: [
      stepOverview,
      stepGoldenRun,
      stepReviewRun,
      stepGovernance,
      stepFailure,
      stepEvidence,
    ],
  },
  {
    id: "deep-dive",
    label: "Technical deep-dive",
    purpose: "Technical reviewer path",
    approximateMinutes: 15,
    intro:
      "For an engineer who wants to read the architecture itself: the " +
      "static export boundary, the adapter / view-model layer, the " +
      "disabled-action discipline, the state-discipline guard, and the " +
      "deferred mutation boundary.",
    steps: [
      stepStaticExportBoundary,
      stepAdapterLayer,
      stepDisabledActionDiscipline,
      stepStateDisciplineGuard,
      stepDeferredBoundary,
    ],
  },
  {
    id: "self-guided",
    label: "Self-guided",
    purpose: "User absent — reviewer can still understand the app",
    approximateMinutes: 7,
    intro:
      "For a reviewer who lands here with no narrator. The goal is to " +
      "answer 'what should I click?', 'what does this prove?', 'what is " +
      "not live?', and 'where is the evidence?' from the GUI alone.",
    steps: [
      stepSelfGuidedOrientation,
      stepGoldenRun,
      stepReviewRun,
      stepSelfGuidedActionBoundary,
      stepSelfGuidedEvidence,
    ],
  },
  {
    id: "governed-chain",
    label: "Governed local chain",
    purpose: "The post-13J governed local-chain story",
    approximateMinutes: 7,
    intro:
      "The governed local-chain story: the modes and boundaries, the " +
      "local-only loopback bridge, the one controlled retry, the manual " +
      "snapshot reload, and the governed mock-first TTS proof. These are " +
      "local-only / operator-boundary surfaces — in the hosted public " +
      "GitHub Pages demo they are gated to static/local-only notices and " +
      "the public site submits no runtime work. Each stop points at a real " +
      "surface; nothing here adds an execution path.",
    steps: [
      stepModes,
      stepBridgeReadiness,
      stepControlledRetry,
      stepManualReload,
      stepTtsProof,
    ],
  },
] as const;

/* ─────────────────────── architecture checkpoints ──────────────── */

/**
 * Architecture-checkpoint cards rendered below the active route. These
 * checkpoints carry the architecture narrative concisely and tied to
 * what the reviewer can inspect in the GUI; a fuller standalone
 * Architecture Story page remains deferred. There are no diagrams,
 * SVGs, or images — only typography, lists, and callout cards.
 */
export interface ArchitectureCheckpoint {
  readonly id: string;
  readonly title: string;
  readonly summary: string;
  readonly inspectableEvidence: readonly string[];
}

export const ARCHITECTURE_CHECKPOINTS: readonly ArchitectureCheckpoint[] = [
  {
    id: "local-first",
    title: "Local-first design",
    summary:
      "StoryTime runs entirely on the operator's machine: a CLI-driven " +
      "pipeline, a local SQLite store, and a static export. No cloud, " +
      "no remote service, and no telemetry is required for the GUI to " +
      "function as you see it now.",
    inspectableEvidence: [
      "The repository ships a `storytime` CLI with `export-demo-ui`.",
      "The committed export JSON is the only data source for the static " +
        "demo path.",
      "The static demo path makes no backend calls; in local execution " +
        "the optional Local Bridge surface adds GET-only loopback " +
        "observability, one controlled retry, and a manual export reload, " +
        "all operator-initiated, and the hosted public demo gates these to " +
        "local-only notices.",
    ],
  },
  {
    id: "deterministic-static-export",
    title: "Deterministic static export",
    summary:
      "The backend emits a typed, deterministic JSON snapshot through " +
      "`storytime export-demo-ui`. The same input produces the same " +
      "export every time, which is what makes a static portfolio build " +
      "honest evidence.",
    inspectableEvidence: [
      "`src/storytime/operator_export.py` is the canonical generator.",
      "`tests/test_operator_export.py` walks and verifies the schema.",
      `Schema version ${EXPORT_META.schemaVersion}; the export remains ` +
        "the stable source of truth for the public static demo.",
    ],
  },
  {
    id: "truth-vs-understanding",
    title: "Backend owns truth, frontend owns understanding",
    summary:
      "The backend records what actually happened: runs, stage timings, " +
      "governance decisions, failure queue entries. The frontend's job " +
      "is to make that intelligible to an operator or reviewer — never " +
      "to invent state, never to re-derive truth at the edge.",
    inspectableEvidence: [
      "Adapters (`adapter.ts`, `governanceAdapter.ts`, `failureAdapter.ts`, " +
        "`evidenceAdapter.ts`, `demoWalkthroughAdapter.ts`) are pure " +
        "projections of the export.",
      "View components hold no domain logic and no fetch calls.",
      "Anything the frontend can't prove from the export is framed as " +
        "deferred, not asserted.",
    ],
  },
  {
    id: "read-only-operator-surface",
    title: "Read-only operator surface",
    summary:
      "The public Phase 15C operator demo is deliberately static and " +
      "read-only across hosted views. Operators can navigate, inspect, " +
      "and understand — but no click in the hosted demo changes pipeline " +
      "state. A real mutation surface is deferred to a future reviewed " +
      "phase.",
    inspectableEvidence: [
      "Every action button that would mutate is a real " +
        "`<button disabled={true}>` with no `onClick`.",
      "The shared `DisabledFutureActionCard` enforces this in one place.",
      "There is no submit, no PATCH/POST/DELETE-shaped helper anywhere.",
    ],
  },
  {
    id: "static-evidence-boundary",
    title: "Static evidence boundary",
    summary:
      "The Evidence / Validation view carries the static-portfolio " +
      "disclaimer — a static portfolio snapshot, not a live CI/CD " +
      "dashboard — and points to repository-relative artifacts " +
      "(verification log, static export contract, deferred-work register, " +
      "phase history, guard tests). Nothing in the GUI fabricates CI " +
      "status.",
    inspectableEvidence: [
      "`docs/verification-log.md` records each round's actual gate runs.",
      "`docs/frontend-static-export-contract.md` documents the contract.",
      "`docs/frontend-gui-deferred-work-register.md` names what is " +
        "deferred and why.",
    ],
  },
  {
    id: "disabled-action-boundary",
    title: "Disabled-action boundary",
    summary:
      "Disabled-action discipline is a contract: every future-action " +
      "affordance in the GUI is a real disabled button with no handler. " +
      "That is what makes the read-only surface honest under inspection.",
    inspectableEvidence: [
      "`DisabledFutureActionCard.tsx` is the shared component.",
      "Governance / Safety, Failure / Recovery, and Pipeline Run Detail " +
        "all consume the shared card.",
      "There is no clickable surface anywhere that fakes a mutation.",
    ],
  },
  {
    id: "data-snapshots",
    title: "Demo / Active / Candidate are data snapshots",
    summary:
      "Demo, Active, and Candidate are data snapshots, NOT deployment " +
      "environments. The public site currently presents one committed " +
      "Demo snapshot; Active and Candidate are placeholders for future " +
      "committed, reviewable static snapshots once the project is run on " +
      "real (non-demo) input. They do not imply backend execution, and " +
      "snapshot switching is not implemented.",
    inspectableEvidence: [
      "The header Data Source chip names the current snapshot.",
      "The Evidence view's Data Source section explains the framing.",
      "Future snapshots would be added only as committed, reviewable " +
        "static data, not as live deployment environments.",
    ],
  },
  {
    id: "governed-local-chain",
    title: "Governed local chain (optional, behind explicit gates)",
    summary:
      "Beyond the static demo, StoryTime has an optional governed local " +
      "chain that landed behind explicit review gates: loopback bridge " +
      "observability, one controlled retry of a failed stage, a manual " +
      "validated export reload, and a governed mock-first local TTS proof. " +
      "These are local-only surfaces, gated to static/local-only notices in " +
      "the hosted public demo. The browser stays an operator surface — " +
      "acceptance is not success, reload is a manual refresh rather than a " +
      "live sync, and generation stays backend/CLI-owned.",
    inspectableEvidence: [
      "`frontend/src/data/localBridgeClient.ts` is GET-only; " +
        "`frontend/src/data/localBridgeActions.ts` submits only " +
        "`retry_failed_stage`.",
      "`frontend/src/data/staticExportReload.ts` performs the one manual, " +
        "validated read-model reload — no polling, sockets, or auto-reload.",
      "`src/storytime/tts_proof/` runs the guarded mock-first proof; " +
        "`docs/demo-walkthrough.md` is the canonical walkthrough and evidence " +
        "map.",
    ],
  },
];

/* ─────────────────────── intentionally deferred ────────────────── */

export interface DeferredItem {
  readonly id: string;
  readonly title: string;
  readonly explanation: string;
}

export const DEFERRED_ITEMS: readonly DeferredItem[] = [
  {
    id: "live-backend",
    title: "No live backend integration",
    explanation:
      "The GUI does not call the backend at runtime. There is no " +
      "`fetch`, no websocket, no long-poll. Everything is the committed " +
      "export.",
  },
  {
    id: "broad-rerun",
    title: "No broad re-run / batch from the GUI",
    explanation:
      "The public GitHub Pages demo submits no runtime work. Controlled " +
      "local actions belong to local execution only and are gated behind " +
      "static/local-only notices in the hosted build: in local execution " +
      "the GUI submits exactly one controlled action — a retry of a failed " +
      "stage — and acceptance is not success (the operator observes the " +
      "lifecycle). Broad re-run, batch runs, and arbitrary actions remain " +
      "deferred.",
  },
  {
    id: "review-write",
    title: "No review write actions",
    explanation:
      "Approve / reject / acknowledge are visibly disabled in the GUI. " +
      "Governance decisions happen out-of-band; the GUI surfaces what " +
      "happened, it does not author it.",
  },
  {
    id: "dynamic-local-loading",
    title: "No file picker / drag-and-drop / remote loader",
    explanation:
      "In local execution the operator can manually reload the committed " +
      "`storytime-demo-export.json` to refresh the transient read model; " +
      "the hosted public demo serves that committed snapshot statically. " +
      "There is no runtime file picker, no drag-and-drop loader, and no " +
      "arbitrary remote fetch. The reload is operator-triggered and validated.",
  },
  {
    id: "snapshot-switching",
    title: "No Demo / Active / Candidate switching",
    explanation:
      "Active and Candidate are framed as future committed, reviewable " +
      "static snapshots, not selectable today. Any future snapshot selector " +
      "would be added only as committed, reviewable static data and does " +
      "not imply backend execution.",
  },
  {
    id: "hosting",
    title: "Public static hosting is live; backend cloud execution deferred",
    explanation:
      "Public static hosting is now live on GitHub Pages: a static, " +
      "read-only, demo-data-backed build. Backend cloud execution remains " +
      "deferred to a future reviewed phase.",
  },
  {
    id: "architecture-story-page",
    title: "No standalone Architecture Story page",
    explanation:
      "The current public demo carries the architecture narrative through " +
      "Overview, Demo Walkthrough, Evidence / Validation, Local Bridge, and " +
      "Live Proof Loop. A fuller standalone Architecture Story page — deeper " +
      "system-boundary explanation, the future backend cloud path, and " +
      "interview leave-behind material — remains deferred and is tracked in " +
      "`docs/frontend-gui-deferred-work-register.md`.",
  },
  {
    id: "frontend-tts-generation",
    title: "No frontend TTS generation",
    explanation:
      "The browser cannot trigger text-to-speech. Generation is owned by " +
      "the backend CLI (`storytime tts-proof`); the GUI only shows read-only " +
      "evidence about the governed proof.",
  },
  {
    id: "real-provider-adapter",
    title: "No provider-backed TTS adapter",
    explanation:
      "The TTS proof uses the deterministic mock provider. A provider-backed " +
      "adapter is not bundled and provider-backed audio remains deferred; " +
      "mock output is labeled mock, not provider audio.",
  },
  {
    id: "audio-playback",
    title: "No in-browser audio playback",
    explanation:
      "There is no audio player. The proof panel describes the artifact, " +
      "manifest, and audit evidence; it does not read or play local " +
      "artifacts.",
  },
  {
    id: "rss-publishing",
    title: "No RSS / episode publishing",
    explanation:
      "Publishing a feed or episodes is deferred. StoryTime today is a " +
      "governed local proof of the content-to-audio chain, not a publisher.",
  },
  {
    id: "full-local-and-cloud",
    title: "No full Local mode or Cloud / Distributed mode",
    explanation:
      "In local execution the surface is the optional loopback bridge plus " +
      "manual reload. A full Local mode and any Cloud / Distributed mode are " +
      "deferred; StoryTime is local-first.",
  },
];

/* ─────────────────────── interview / SE talking points ──────────── */

export interface TalkingPoint {
  readonly id: string;
  readonly label: string;
  readonly body: string;
}

export const INTERVIEW_TALKING_POINTS: readonly TalkingPoint[] = [
  {
    id: "observability-native",
    label: "Observability-native pipeline thinking",
    body:
      "Every stage has measured timing and a clear status surfaced in " +
      "the operator GUI. Observability is not a dashboard added later — " +
      "it is the substrate the pipeline runs on.",
  },
  {
    id: "governance-visibility",
    label: "Governance visibility",
    body:
      "The Governance / Safety view shows policy outcomes per run. " +
      "Reviewers don't have to read logs to know whether a gate fired " +
      "and why.",
  },
  {
    id: "failure-visibility",
    label: "Failure / recovery visibility",
    body:
      "The Failure / Recovery view exposes the failure queue with " +
      "reason and timestamps. Operational state is observable, even " +
      "when the resolution still happens in the CLI.",
  },
  {
    id: "static-proof",
    label: "Static proof boundaries",
    body:
      "The Evidence / Validation view declares it is a static portfolio " +
      "snapshot, not a live CI/CD dashboard, and points to real repository " +
      "files. The portfolio earns trust by being honest about what it is.",
  },
  {
    id: "mutation-discipline",
    label: "Safe mutation-boundary discipline",
    body:
      "State-changing actions stay real disabled buttons, with one " +
      "deliberate exception that landed behind explicit review and runs in " +
      "local execution only: a single controlled retry of a failed stage " +
      "over the local loopback bridge. The hosted public demo submits no " +
      "runtime work and gates that surface to a local-only notice. " +
      "Acceptance is not success, and the operator must observe the " +
      "lifecycle. Every other mutation stays gated rather than smuggled in. " +
      "That is portfolio-grade discipline.",
  },
  {
    id: "portfolio-value",
    label: "Portfolio value",
    body:
      "A static, read-only, export-backed GUI over a local pipeline is " +
      "exactly the right artifact for a portfolio: reviewers can run it " +
      "themselves, every claim is inspectable, and nothing depends on a " +
      "hosted service to remain truthful.",
  },
  {
    id: "governed-tts-proof",
    label: "Governed local TTS proof",
    body:
      "StoryTime proves the content-to-audio step through a governed, " +
      "observable, auditable backend boundary: an approved fixture driven " +
      "through a governance/cost guard and a deterministic mock provider to " +
      "one atomic local artifact, with a manifest and an audit/event " +
      "lifecycle. Source text is recorded as a hash and character count, " +
      "never raw text. Provider-backed audio remains deferred, and the " +
      "browser cannot trigger generation.",
  },
  {
    id: "local-bridge-boundary",
    label: "Local bridge boundary",
    body:
      "The optional Local Bridge is local-only, loopback-only " +
      "infrastructure: read-only observability over GET, plus exactly one " +
      "controlled retry submitted over a single POST in local execution. It " +
      "is not exposed to the public web, is gated to a local-only notice in " +
      "the hosted public demo, and carries no browser credentials. The " +
      "browser is an operator surface; the backend owns execution and state.",
  },
];

/* ─────────────────────── repository references ──────────────────── */

export interface RepoRef {
  readonly label: string;
  readonly path: string;
  readonly hint: string;
}

export const REPOSITORY_REFERENCES: readonly RepoRef[] = [
  {
    label: "Backend export generator",
    path: "src/storytime/operator_export.py",
    hint: "Emits the typed JSON the entire GUI reads.",
  },
  {
    label: "Committed static export",
    path: "frontend/src/data/storytime-demo-export.json",
    hint: "The one and only runtime data source for this build.",
  },
  {
    label: "Static export contract",
    path: "docs/frontend-static-export-contract.md",
    hint: "Documents the contract the GUI depends on.",
  },
  {
    label: "Deferred-work register",
    path: "docs/frontend-gui-deferred-work-register.md",
    hint: "Names every deferred item, including the standalone " +
      "Architecture Story page.",
  },
  {
    label: "State-discipline guard",
    path: "tests/test_failure_mode_regression.py",
    hint: "Mechanically enforces phase / lock / no-overclaim state.",
  },
  {
    label: "Phase history",
    path: "docs/phase-history.md",
    hint: "Append-only record of every round and lock.",
  },
  {
    label: "Canonical demo walkthrough",
    path: "docs/demo-walkthrough.md",
    hint: "Single source of truth for the reviewer/demo path + evidence map.",
  },
  {
    label: "Local bridge backend",
    path: "src/storytime/local_bridge/",
    hint: "Loopback bridge: read-only observability + one controlled retry.",
  },
  {
    label: "Controlled retry action",
    path: "frontend/src/data/localBridgeActions.ts",
    hint: "Submits only retry_failed_stage; acceptance is not success.",
  },
  {
    label: "Manual static export reload",
    path: "frontend/src/data/staticExportReload.ts",
    hint: "The one operator-triggered, validated read-model reload.",
  },
  {
    label: "Governed TTS proof",
    path: "src/storytime/tts_proof/",
    hint: "Guarded mock-first chain to atomic artifact, manifest, and audit.",
  },
  {
    label: "Operator console vocabulary",
    path: "frontend/src/data/operatorConsole.ts",
    hint: "Mode/boundary/TTS-proof language the walkthrough narrates.",
  },
];

/* ─────────────────────── header copy ─────────────────────────── */

/**
 * Static copy for the Demo Walkthrough header. Kept here so the view
 * file stays a presentation shell.
 */
export const HEADER = {
  eyebrow: "Reviewer story path · static walkthrough",
  title: "Demo Walkthrough",
  lede:
    `A guided reviewer / demo path through the existing ${DEMO_PROJECT.name} ` +
    "operator GUI. Pick a route to fit your time budget; each step tells " +
    "you what to inspect, what it proves, and what to say about it. Most " +
    "steps link into read-only views; the Local Bridge and Live Proof Loop " +
    "are local-only / operator-boundary surfaces — gated to static/local-only " +
    "notices in the hosted public demo, where they demonstrate loopback " +
    "observability, one controlled retry, and a manual snapshot reload in " +
    "local execution — and the governed TTS proof appears as read-only " +
    "evidence. See docs/demo-walkthrough.md for the canonical written " +
    "walkthrough and the evidence map.",
} as const;

/* ─────────────────────── sanity exports for tests / introspection ── */

/**
 * A small convenience for any test or future view that wants to know
 * which run ids the walkthrough references. Kept narrow on purpose.
 */
export const REFERENCED_RUN_IDS: readonly string[] = [
  GOLDEN_RUN_ID,
  REVIEW_RUN_ID,
];

/**
 * Convenience — the count of run summaries the wider GUI shows. Nothing
 * depends on this number being any particular value; it exists so a
 * future test or sanity log line can reason about it without
 * re-importing the adapter elsewhere.
 */
export const RUN_SUMMARY_COUNT = DEMO_RUN_SUMMARIES.length;
